=== tizerus/BookMySQLReader/bin/books_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/books_schema" 
	xmlns:tns="http://www.it-academy.by/books_schema"
	elementFormDefault="qualified">

	<xs:element name="books" type="tns:books_type"></xs:element>
	
	<xs:complexType name="books_type">
		<xs:sequence>
			<xs:element name="book" type="tns:book_type" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="book_type">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="author" type="tns:author_type" minOccurs="1" maxOccurs="2"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>
	
	<xs:complexType name="author_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
			<xs:element name="date" type="xs:date" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== tizerus/BookMySQLReader/bin/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.it-academy.by/books_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.it-academy.by/books_schema books_schema.xsd">

	
	<book id="1">
		<title>Book1</title>
		<pages>345</pages>
		<author>
			<name>Viktor</name>
			<surname>Ivanov</surname>
			<date>1987-04-21</date>
		</author>
		
	</book>
	<book id="2">
		<title>Book2</title>
		<pages>218</pages>
		<author>
			<name>Petr</name>
			<surname>Petrov</surname>
			<date>1997-01-01</date>
		</author>
	</book>
</books>
